title: Jose Anthony # your name (or website title) here
logo: "/images/me.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Informatics Fresh Graduate at BINUS University.
  Enthusiastic and a fast learner. I'm looking for more
  experience to improve myself on an organization and
  working environment.  I have a big
  commitment for every work that I do and with a high
  sense of responsibility, I strive for a job well done.
  <br><br>
  Currently studying independently as a 
  Front End engineer at GenerasiGIGIH2.0
  <br><br>
  Bandung, West Java, Indonesia
  <br><br>
  <a href="https://www.linkedin.com/in/cykrya/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

