title: Jose Anthony # your name (or website title) here
logo: "/images/me.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Informatics Undergraduate at BINUS University
  <br><br>
  Bandung, West Java, Indonesia
  <br><br>
  <a href="www.linkedin.com/in/cykrya/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
